### ISSUE TITLE
Spring AOP Advices cannot be used together with qbit 

### ISSUE THREAD

**Issue by alexey-kanashevich** [advantageous/qbit#488] opened 2015-10-26 12:58 UTC
It is due to proxy produced by spring, solution can be cast to proxy class and get target class.
Advised advised = (Advised) proxy;
Class<?> cls = advised.getTargetSource().getTargetClass();

Have no idea how to workaround this in boon.

http://docs.spring.io/spring/docs/4.2.x/javadoc-api/org/springframework/aop/support/AopUtils.html#getTargetClass
Exception in thread "main" MESSAGE: name preFiltered setter public abstract void org.springframework.aop.framework.Advised.setPreFiltered(boolean) getter public abstract boolean org.springframework.aop.framework.Advised.isPreFiltered()
 CAUSE io.advantageous.boon.core.Exceptions$SoftenedException :: Unable to extract annotation for property preFiltered  of class  interface org.springframework.aop.framework.Advised   useRead  false
io.advantageous.boon.core.Exceptions$SoftenedException: name preFiltered setter public abstract void org.springframework.aop.framework.Advised.setPreFiltered(boolean) getter public abstract boolean org.springframework.aop.framework.Advised.isPreFiltered()
 CAUSE io.advantageous.boon.core.Exceptions$SoftenedException :: Unable to extract annotation for property preFiltered  of class  interface org.springframework.aop.framework.Advised   useRead  false

 CAUSE io.advantageous.boon.core.Exceptions$SoftenedException :: Required object assertion exception
	at io.advantageous.boon.core.Exceptions.handle(Exceptions.java:164)
	at io.advantageous.boon.core.reflection.fields.BaseField.<init>(BaseField.java:313)
	at io.advantageous.boon.core.reflection.fields.PropertyField.<init>(PropertyField.java:46)
	at io.advantageous.boon.core.reflection.Reflection.getPropertyFieldAccessors(Reflection.java:625)
	at io.advantageous.boon.core.reflection.ClassMeta.<init>(ClassMeta.java:180)
	at io.advantageous.boon.core.reflection.ClassMeta.classMeta(ClassMeta.java:273)
	at io.advantageous.qbit.service.impl.BoonServiceMethodCallHandler.init(BoonServiceMethodCallHandler.java:603)
	at io.advantageous.qbit.service.impl.BaseServiceQueueImpl.<init>(BaseServiceQueueImpl.java:170)
	at io.advantageous.qbit.service.impl.ServiceQueueImpl.<init>(ServiceQueueImpl.java:50)
	at io.advantageous.qbit.service.ServiceBuilder.build(ServiceBuilder.java:423)
	at io.advantageous.qbit.service.ServiceBuilder.buildAndStart(ServiceBuilder.java:444)
	at io.advantageous.qbit.service.impl.ServiceBundleImpl.addServiceObject(ServiceBundleImpl.java:312)
	at io.advantageous.qbit.service.impl.ServiceBundleImpl.addService(ServiceBundleImpl.java:249)
	at io.advantageous.qbit.server.ServiceEndpointServerImpl.initServices(ServiceEndpointServerImpl.java:365)
	at io.advantageous.qbit.server.EndpointServerBuilder.build(EndpointServerBuilder.java:619)
	at com.mm.base.Main.main(Main.java:24)
Caused by: io.advantageous.boon.core.Exceptions$SoftenedException: Unable to extract annotation for property preFiltered  of class  interface org.springframework.aop.framework.Advised   useRead  false

```

**Comment by alexey-kanashevich** [comment] 2015-10-26 14:12
one of possible workaround can be load or compile time weaving, still looking for better solution

**Comment by RichardHightower** [comment] 2015-10-26 17:10
I need a test case. Some sample code. A unit test. If I can't reproduce it, I can't fix it. Or know even if it is something that I deem worth fixing. So please add more details or I will have to close as wontfix.

**Comment by alexey-kanashevich** [comment] 2015-10-27 08:04
https://github.com/alexey-kanashevich/qbit-jwt-auth
Run Main.

**Comment by RichardHightower** [comment] 2015-10-28 20:33
I was able to run this and track it down. The code that causes this bug lives here.

https://github.com/advantageous/boon

I will move this report to there.

**Comment by RichardHightower** [comment] 2015-10-28 20:34
Moved here:

https://github.com/advantageous/boon/issues/5

(working on a fix)

**Comment by RichardHightower** [comment] 2015-10-28 20:44
Fixed.

**Closed** 2015-10-28 20:44 UTC

**Comment by RichardHightower** [comment] 2015-10-28 20:45
https://github.com/advantageous/qbit/commit/4273ca22d2871442d605dacd6207dbd13905a9f7

**Comment by RichardHightower** [comment] 2015-10-28 20:46
Build snapshot version.

**Comment by RichardHightower** [comment] 2015-10-28 20:49
@fadihub can you do a RC release of adv/boon and adv/qbit and cut/paste info here. 

Thanks man.

**Comment by fadihub** [comment] 2015-10-29 02:33
Boon version 0.5.6-RC2 and QBit version 0.9.1-RC13 (depends on boon
0.5.6-RC2) are released.

Regards


On Wed, Oct 28, 2015 at 1:49 PM, Richard Hightower <notifications@github.com

**Comment by RichardHightower** [comment] 2015-10-29 03:02
Awesome!

**Comment by alexey-kanashevich** [comment] 2015-10-30 11:29
Thanks. Have looked into fix. If I understand correctly I lose swagger support for endpoint controller if I use proxy.

**Comment by RichardHightower** [comment] 2015-11-01 18:30
Not that I know of, but report another issue if that is the case.
